# Builds the Unity Editor plugin on macOS and Windows
name: unity-editor-plugin

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  unity-editor-plugin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: rust-core-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rustup macOS targets (universal dylib)
        if: runner.os == 'macOS'
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
        shell: bash

      - name: Run CI script
        run: sh ci-unity-editor-plugin.sh
        shell: bash

      - name: Upload Unity editor plugin (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: unity-editor-plugin-macos
          path: interfaces/unity/NiceVibrations/Assets/NiceVibrations/Plugins/macOS/

      - name: Upload Unity editor plugin (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: unity-editor-plugin-windows
          path: interfaces/unity/NiceVibrations/Assets/NiceVibrations/Plugins/Windows/x64/


